#config_version=5

show_player:
  mode_attract_started:
    attract_display_loop:
      speed: 1
    #new_rainbow_swirl:
    #  speed: 80
    output6:
      speed: 20
#    general_illumination:
#      speed: 1

sound_player:
  mode_attract_started:
    main:
      action: stop
    song01:
      action: play
      loops: -1
  mode_attract_stopped:
    song01:
      action: stop
