#config_version=5
mode:
  start_events: ball_started
  priority: 100

show_player:
  mode_base_started.1: general_illumination
  mode_base_started.2:
    police_saucer:
      speed: 8

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50

variable_player:
  s_right_inlane_active:
    score: 5000
  s_right_slingshot_active:
    score: 100
  s_right_outlane_active:
    score: 1000
    bonus: 10000
  s_lower_right_rebound_active:
    score: 10
  s_captive_ball_target_active:
    score: 10000
  s_advance_bonus_standup_active:
    score: 1000
    bonus: 10000
  s_upper_rebound_left_active:
    score: 100
  s_upper_rebound_right_active:
    score: 100
  s_pop_bumper_active:
    score: 1000
  s_left_inlane_active:
    score: 5000
  s_left_outlane_active:
    score: 1000
    bonus: 10000
  s_left_slingshot_active:
    score: 10
  s_lower_rebound_left_active:
    score: 10
  s_spinner_active:
    score: 100
  s_left_saucer_active:
    score: 5000
    bonus: 10000
  s_left_middle_rebound_active:
    score: 10
