#config_version=5

mode_settings:
  display_delay_ms: 1s
  hurry_up_delay_ms: 0
  bonus_entries:
    - event: bonus_ladder
      score: 10000
slide_player:
  bonus_total: bonus_total_slide
slides:
  bonus_total_slide:
    - type: text
      text: "Total Bonus"
    - type: text
      text: (score)
