#config_version=5
mode_settings:
  display_delay_ms: 1s
  hurry_up_delay_ms: 0
  bonus_entries:
    - event: bonus_points
      score: 10000 * (current_player.bonus_points)
slide_player:
  mode_bonus_started: bonus_start_slide
  bonus_total: bonus_total_slide
slides:
  bonus_start_slide:
    widgets:
      - type: text
        text: Bonus
    transition:
      type: move_in
      duration: 1s
      direction: right
  bonus_total_slide:
    widgets:
      - type: text
        text: "Total Bonus"
        y: 10
        x: 10
      - type: text
        text: (score)
    transition:
      type: move_in
      duration: 1s
      direction: right
