#config_version=5

coils:
  c_flipper_left:
    number:
    allow_enable: true
  c_flipper_righ:
    number:
    allow_enable: true
  c_trough:
    number:
    default_pulse_ms: 8
  c_left_sling:
    number:
    default_pulse_ms: 8
  c_right_sling:
    number:
    default_pulse_ms: 8
  c_left_saucer:
    number:
    default_pulse_ms: 8
  c_pop:
    number:
    default_pulse_ms: 8
  c_drop_left:
    number:
    default_pulse_ms: 8
  c_drop_right:
    number:
    default_pulse_ms: 8
  c_top_saucer:
    number:
    default_pulse_ms: 8

#low priority to wire up
#  c_knocker:
#    number:
#    default_pulse_ms: 20
#  c_chime_low:
#    number:
#    default_pulse_ms: 20
#  c_chime_medium:
#    number:
#    default_pulse_ms: 20
#  c_chime_large:
#    number:
#    default_pulse_ms: 20


#future coil ideas
#control gates on upper area
#auto plunge coil
#ball trough coils
#disapearing post for captive ball multiball idea
#control gates to reload captive ball
