#config_version=5

#For PD-16-based devices, the numbering format is:
#
#number: Ax-By-z
#
#The “A” and “B” capital letters are required.
#   A means Address, B means Bank The
#The lowercase x, y, and z letters
#    x : Board address (0-31)
#    y : Bank address (0 for A, 1 for B)
#    z : Output number (0-7)


coils:
  c_flipper_left:
    number: A0-B0-1
    allow_enable: true
    default_hold_power: 0.125
  c_flipper_right:
    number: A0-B1-2
    allow_enable: true
    default_hold_power: 0.125
  c_trough:
    number: A0-B1-3
    default_pulse_ms: 8
  c_left_sling:
    number: A0-B0-2
    default_pulse_ms: 8
  c_right_sling:
    number: A0-B1-4
    default_pulse_ms: 8
  c_left_saucer:
    number: A0-B0-3
    default_pulse_ms: 8
  c_pop:
    number: A0-B1-5
    default_pulse_ms: 8
  c_drop_left:
    number: A0-B0-4
    default_pulse_ms: 8
  c_drop_right:
    number: A0-B1-6
    default_pulse_ms: 8
  c_top_saucer:
    number: A0-B0-5
    default_pulse_ms: 8

#low priority to wire up
#  c_knocker:
#    number:
#    default_pulse_ms: 20
#  c_chime_low:
#    number:
#    default_pulse_ms: 20
#  c_chime_medium:
#    number:
#    default_pulse_ms: 20
#  c_chime_large:
#    number:
#    default_pulse_ms: 20


#future coil ideas    #48 V required? Or alt coils
#control gates on upper area
#auto plunge coil
#ball trough coils
#disapearing post for captive ball multiball idea
#control gates to reload captive ball
