#config_version=5

#hardware:
#  platform: p3_roc
#  driverboards: pdb
#

switches:
 s_left_flipper:
   number:
   tags: left_flipper
 s_right_flipper:
   number:
   tags: right_flipper
 s_outhole:
   number:
   tags: outhole
 s_right_inlane:
   number:
 s_left_inlane:
   number:
 s_right_outlane:
   number:
 s_left_outlane:
   number:
 s_left_slingshot:
   number:
 s_right_slingshot:
   number:
 s_captive_ball_lane:
   number:
 s_captive_ball_target:
   number:

coils:
 c_flipper_left_main:
   number: 
   default_pulse_ms: 20
 c_flipper_left_hold:
   number:
   allow_enable: true
 c_flipper_right_main:
   number:
   default_pulse_ms: 20
 c_flipper_right_hold:
   number:
   allow_enable: true
 c_outhole_kicker:
   number:
   default_pulse_ms: 20

playfields:
  playfield:
   tags: default
   default_source_device: bd_trough

flippers: #flippers activated after boot for testing
 left_flipper:
   main_coil: c_flipper_left_main
   hold_coil: c_flipper_left_hold
   activation_switch: s_left_flipper
   enable_events: machine_reset_phase_3 #allow flippers after boot for testing
 right_flipper:
   main_coil: c_flipper_right_main
   hold_coil: c_flipper_right_hold
   activation_switch: s_right_flipper
   enable_events: machine_reset_phase_3 #allow flippers after boot for testing

keyboard:
  z:
    switch: s_left_flipper
  x:
    switch: s_right_flipper

ball_devices:
  bd_trough:
    ball_switches: s_outhole
    eject_coil: c_outhole_kicker
    tags: trough, home, drain
    debug: yes


virtual_platform_start_active_switches:
  s_outhole #ball starts in outhole when loading virtual instance of game
