#config_version=5

config:
  - switches.yaml
  - lamps.yaml
  - hardware.yaml
  - audio_config.yaml


modes:
  - base
  - bonus
  - tilt

displays:
  window:
    width: 800
    height: 600
