#config_version=5

config:
  - switches.yaml
  - keyboard.yaml
  - coils.yaml

modes:
  - base

playfields:
  playfield:
   tags: default
   default_source_device: bd_trough

flippers: #flippers activated after boot for testing
 left_flipper:
   main_coil: c_flipper_left_main
   hold_coil: c_flipper_left_hold
   activation_switch: s_left_flipper
   enable_events: machine_reset_phase_3 #allow flippers after boot for testing
 right_flipper:
   main_coil: c_flipper_right_main
   hold_coil: c_flipper_right_hold
   activation_switch: s_right_flipper
   enable_events: machine_reset_phase_3 #allow flippers after boot for testing

ball_devices:
  bd_trough:
    ball_switches: s_outhole
    eject_coil: c_outhole_kicker
    tags: trough, home, drain
    # debug: yes
  bd_left_saucer:
    ball_switches: s_left_saucer
    eject_coil: c_left_saucer
    eject_timeouts: 500ms
  bd_top_saucer:
    ball_switches: s_top_saucer
    eject_coil: c_top_saucer
    eject_timeouts: 500ms

autofire_coils: #possibly needs to be configured on a mode level basis, or need to figure out how to disable in a mode like super-plunge
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  pop_bumper:
    coil: c_pop_bumper
    switch: s_pop_bumper

virtual_platform_start_active_switches:
  s_outhole #ball starts in outhole when loading virtual instance of game

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60
  attract_started:
    widgets:
      - text: ATTRACT MODE
        type: text

slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started