#config_version=5

hardware:
  platform: p3_roc
  driverboards: pdb

playfields:
  playfield:
   tags: default
   default_source_device: bd_trough

ball_devices:
  bd_trough:
    ball_switches: s_outhole
    eject_coil: c_trough
    tags: trough, home, drain
  bd_left_saucer:
    ball_switches: s_left_saucer
    eject_coil: c_left_saucer
    eject_timeouts: 500ms
  bd_top_saucer:
    ball_switches: s_top_saucer
    eject_coil: c_top_saucer
    eject_timeouts: 800ms

autofire_coils:
  afc_left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  afc_right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  afc_pop_bumper:
    coil: c_pop
    switch: s_pop_bumper

drop_targets:
  drop_left_left:
    switch: s_left_drop_left
    reset_coil: c_drop_left
  drop_left_center:
    switch: s_left_drop_center
    reset_coil: c_drop_left
  drop_left_right:
    switch: s_left_drop_right
    reset_coil: c_drop_left
  drop_right_left:
    switch: s_right_drop_left
    reset_coil: c_drop_right
  drop_right_center:
    switch: s_right_drop_center
    reset_coil: c_drop_right
  drop_right_right:
    switch: s_right_drop_right
    reset_coil: c_drop_right


drop_target_banks:
  drop_both:
    drop_targets: drop_left_left, drop_left_center, drop_left_right, drop_right_left, drop_right_center, drop_right_right
    reset_coils: c_drop_left, c_drop_right
    reset_on_complete: 500ms

#split drop target banks
#drop_target_banks:
#  drop_left:
#    drop_targets: drop_left_left, drop_left_center, drop_left_right
#    reset_coils: c_drop_left
#    reset_on_complete: 500ms
#  drop_right:
#    drop_targets: drop_right_left, drop_right_center, drop_right_right
#    reset_coils: c_drop_right
#    reset_on_complete: 500ms

coils:
  c_trough:
    number: A0-B1-3
    default_pulse_ms: 20
  c_left_saucer:
    number: A0-B0-3
    default_pulse_ms: 15
  c_top_saucer:
    number: A0-B0-5
    default_pulse_ms: 12
  c_left_slingshot:
    number: A0-B0-2
    default_pulse_ms: 15
  c_right_slingshot:
    number: A0-B1-4
    default_pulse_ms: 15
  c_pop:
    number: A0-B1-5
    default_pulse_ms: 18
  c_drop_left:
    number: A0-B0-4
    default_pulse_ms: 53
  c_drop_right:
    number: A0-B1-6
    default_pulse_ms: 38
  c_flipper_left:
    number: A0-B0-1
    allow_enable: true
    default_pulse_ms: 1
  c_flipper_right:
    number: A0-B1-2
    allow_enable: true
    default_pulse_ms: 1

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_right_flipper

virtual_platform_start_active_switches: #ball starts in outhole when loading virtual instance of game
  s_outhole
