#config_version=5

keyboard:
  s:
    switch: s_credit_button
  z:
    switch: s_left_flipper
  x:
    switch: s_right_flipper
  o:
    switch: s_outhole
  q:
    switch: s_left_outlane
  w:
    switch: s_left_inlane
  e:
    switch: s_left_slingshot
  r:
    switch: s_right_slingshot
  t:
    switch: s_right_inlane
  y:
    switch: s_right_outlane

  
