#config_version=5
lights:

#PD-LED-1
  #J5 LA1
    l_:
      number: 1-0-1-2
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-3-4-5
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-6-7-8
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-9-10-11
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J9 LA2
    l_:
      number: 1-12-13-14
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-15-16-17
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-18-19-20
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-21-22-23
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J6 LA3
    l_:
      number: 1-24-25-26
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-27-28-29
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-30-31-32
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-33-34-35
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J10 LA4
    l_:
      number: 1-36-37-38
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-39-40-41
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-42-43-44
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-45-46-47
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J7 LA5
    l_:
      number: 1-48-49-50
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-51-52-53
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-54-55-56
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-57-58-59
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J11 LA6
    l_:
      number: 1-60-61-62
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-63-64-65
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-66-67-68
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-69-70-71
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J8 LA7
    l_:
      number: 1-72-73-74
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-75-76-77
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-78-79-80
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 1-81-82-83
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true

#PD-LED-2
  #J5 LB1
    l_:
      number: 2-0-1-2
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-3-4-5
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-6-7-8
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-9-10-11
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J9 LB2
    l_:
      number: 2-12-13-14
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-15-16-17
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-18-19-20
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-21-22-23
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J6 LB3
    l_:
      number: 2-24-25-26
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-27-28-29
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-30-31-32
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-33-34-35
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J10 LB4
    l_:
      number: 2-36-37-38
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-39-40-41
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-42-43-44
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-45-46-47
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J7 LB5
    l_:
      number: 2-48-49-50
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-51-52-53
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-54-55-56
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-57-58-59
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
  #J11 LB6
    l_:
      number: 2-60-61-62
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-63-64-65
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-66-67-68
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
    l_:
      number: 2-69-70-71
        subtype: led
        fade_ms: 40ms
        tags:
        label:
        platform_settings:
          polarity: true
#  #J8 LB7 # UNUSED
#    l_:
#      number: 2-72-73-74
#        subtype: led
#        fade_ms: 40ms
#        tags:
#        label:
#        platform_settings:
#          polarity: true
#    l_:
#      number: 2-75-76-77
#        subtype: led
#        fade_ms: 40ms
#        tags:
#        label:
#        platform_settings:
#          polarity: true
#    l_:
#      number: 2-78-79-80
#        subtype: led
#        fade_ms: 40ms
#        tags:
#        label:
#        platform_settings:
#          polarity: true
#    l_:
#      number: 2-81-82-83
#        subtype: led
#        fade_ms: 40ms
#        tags:
#        label:
#        platform_settings:
#          polarity: true
