#config_version=5

lights:
  l_B3:
    number: 1-0-1-2
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_B2:
    number: 1-3-4-5
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_B1:
    number: 1-6-7-8
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_Shoot_Again:
    number: 1-9-10-11
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_B4:
    number: 1-12-13-14
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_B5:
    number: 1-15-16-17
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_R_out:
    number: 1-18-19-20
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_sling:
    number: 1-21-22-23
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_out:
    number: 1-24-25-26
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_sling:
    number: 1-27-28-29
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_B6:
    number: 1-30-31-32
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_B7:
    number: 1-33-34-35
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_CBall_GI_High:
    number: 1-36-37-38
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_CBall_GI_Low:
    number: 1-39-40-41
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Mid_GI:
    number: 1-42-43-44
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_CBall_Arrow:
    number: 1-45-46-47
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Mid_GI:
    number: 1-48-49-50
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Saucer_Insert:
    number: 1-51-52-53
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Spinner_Arrow:
    number: 1-54-55-56
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Saucer_GI:
    number: 1-57-58-59
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_B8:
    number: 1-60-61-62
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_B9:
    number: 1-63-64-65
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_B10:
    number: 1-66-67-68
    subtype: led
    fade_ms: 50ms
    tags: bonus
    platform_settings:
      polarity: true
  l_Horse1:
    number: 1-69-70-71
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Pop:
    number: 1-72-73-74
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Horse2:
    number: 1-75-76-77
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Double_Bonus:
    number: 1-78-79-80
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Horse3:
    number: 1-81-82-83
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Drop_Low_In:
    number: 2-0-1-2
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Drop_Top_In:
    number: 2-3-4-5
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Drop_Top_In:
    number: 2-6-7-8
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Drop_Low_In:
    number: 2-9-10-11
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_CBall_GI:
    number: 2-12-13-14
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Drop_R_GI:
    number: 2-15-16-17
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Drop_L_GI:
    number: 2-18-19-20
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Drop_GI:
    number: 2-21-22-23
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Drop_GI_High:
    number: 2-24-25-26
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Drop_GI_Low:
    number: 2-27-28-29
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Drop_L_GI:
    number: 2-30-31-32
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Spinner_GI:
    number: 2-33-34-35
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Saucer1:
    number: 2-36-37-38
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Rebound:
    number: 2-39-40-41
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Drop_GI_R:
    number: 2-42-43-44
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_L_Top_Inlane:
    number: 2-45-46-47
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Saucer5:
    number: 2-48-49-50
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Saucer4:
    number: 2-51-52-53
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Saucer3:
    number: 2-54-55-56
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_Saucer2:
    number: 2-57-58-59
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Top_GI:
    number: 2-63-64-65
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Rebound:
    number: 2-66-67-68
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_R_Top_Inlane:
    number: 2-69-70-71
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
