#config_version=5

switches:
  s_outhole:
    number: A0-B0-0
  s_right_inlane:
    number: A0-B0-1
  s_right_slingshot:
    number: A0-B0-2
  s_right_outlane:
    number: A0-B0-3
  s_lower_right_rebound:
    number: A0-B0-4
  s_captive_ball_rollover:
    number: A0-B0-5
  s_captive_ball_target:
    number: A0-B0-6
  s_advance_bonus_standup:
    number: A0-B0-7
  s_right_drop_center:
    number: A0-B1-0
  s_right_drop_right:
    number: A0-B1-1
  s_left_drop_right:
    number: A0-B1-2
  s_left_drop_left:
    number: A0-B1-3
  s_right_drop_left:
    number: A0-B1-4
  s_left_drop_center:
    number: A0-B1-5
#  s_15: UNUSED
#    number: A0-B1-6
#  s_16: UNUSED
#    number: A0-B1-7
  s_plumb_bomb_tilt:
    number: A1-B0-0
  s_start:
    number: A1-B0-1
    tags: start
  s_left_flipper:
    number: A1-B0-2
  s_right_flipper:
    number: A1-B0-3
  s_upper_rebound_left:
    number: A1-B0-4
  s_upper_rebound_right:
    number: A1-B0-5
  s_top_saucer:
    number: A1-B0-6
  s_pop_bumper:
    number: A1-B0-7
  s_left_inlane:
    number: A1-B1-0
  s_left_outlane:
    number: A1-B1-1
  s_left_slingshot:
    number: A1-B1-2
  s_lower_rebound_left:
    number: A1-B1-3
  s_spinner:
    number: A1-B1-4
  s_left_saucer:
    number: A1-B1-5
  s_left_middle_rebound:
    number: A1-B1-6
  s_left_top_rollover:
    number: A1-B1-7
