#config_version=5

switches:
#playfield
  s_outhole:
    number: A1-B0-0
    tags: outhole
  s_right_inlane:
    number: A1-B0-1
    tags: playfield_active
  s_left_inlane:
    number: A1-B1-0
    tags: playfield_active
  s_right_outlane:
    number: A1-B0-3
    tags: playfield_active
  s_left_outlane:
    number: A1-B1-1
    tags: playfield_active
  s_left_sling:
    number: A1-B1-2
    tags: #playfield_active
  s_right_sling:
    number: A1-B0-2
    tags: #playfield_active
  s_captive_ball_rollover:
    number: A1-B0-5
    tags: playfield_active
  s_captive_ball_target:
    number: A1-B0-6
    tags: playfield_active
  s_drop_l_1:
    number: A0-B1-0
  s_drop_l_2: #26
    number: A0-B1-1
  s_drop_l_3: #25
    number: A0-B1-2
  s_drop_r_1: #19
    number: A0-B1-3
  s_drop_r_2: #18
    number: A0-B1-4
  s_drop_r_3: #17
    number: A0-B1-5
  s_upper_rebound_left:
    number: A0-B0-4
    tags: playfield_active
  s_upper_rebound_right:
    number: A0-B0-5
    tags: playfield_active
  s_lower_rebound_right:
    number: A1-B0-4
    tags: playfield_active
  s_advance_bonus_standup:
    number: A1-B0-7
    tags: playfield_active
  s_top_saucer:
    number: A0-B0-6
  s_left_top_rollover:
    number: A1-B1-7
    tags: playfield_active
  s_middle_left_rebound:
    number: A1-B1-6
    tags: playfield_active
  s_left_saucer:
    number: A1-B1-5
  s_spinner:
    number: A1-B1-4
    tags: playfield_active
  s_pop_bumper:
    number: A0-B0-7
    tags: #playfield_active
  s_lower_rebound_left:
    number: A1-B1-3
    tags: playfield_active

#coin door
  s_credit_button:
    number:
    tags: start

#CABINET
  s_left_flipper:
    number: A0-B0-0
    tags: playfield_active, left_flipper
  s_right_flipper:
    number: A0-B0-1
    tags: playfield_active, right_flipper
  s_plumb_bomb_tilt:
    number:
    tags: playfield_active, tilt_warning


#  s_right_coin:
#    number:
#  s_center_coin:
#    number:
#  s_left_coin:
#    number:
#anti-cheat

#  s_ball_roll_tilt:
#    number:
#    tags: slam_tilt
#  s_slam_tilt:
#    number:
#    tags: slam_tilt
#  s_playfield_tilt:
#    number:
#    tags: slam_tilt

#need to add shooter lane switch
#need to add ball trough switches if installed
